
KalamuCmsAdminBundle_elfinder:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/elfinder.yml"
    prefix:   /elfinder

KalamuCmsAdminBundle_link_picker_api:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/api_link_picker.yml"
    prefix:   /api/link_picker


KalamuCmsAdminBundle_menu:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

# Route for the dashboards API (admin homepage and edition)
kalamu_default_site_dashboard_api:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/dashboard_api.yml"
    prefix:   /dashboard_storage/api

# Routes for login / check login / logout
fos_user_security:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/security.yml"
    prefix: /