fos_user_security_login:
    path:     /login
    defaults: { _controller: KalamuCmsAdminBundle:Admin\Security:login }

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: KalamuCmsAdminBundle:Admin\Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: KalamuCmsAdminBundle:Admin\Security:logout }

# Routes for user profile
fos_user_security_profile:
    path:     /profile
    defaults: { _controller: KalamuCmsAdminBundle:Admin\Security:profile }

fos_user_security_profile_edit:
    path:     /profile/edit
    defaults: { _controller: KalamuCmsAdminBundle:Admin\Security:profileEdit }